/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc20Sol from "./MockERC20.sol";
export type { mockErc20Sol };
export type { Lock } from "./Lock";
export type { OtterPadFundraiser } from "./OtterPadFundraiser";
export type { ReentrantToken } from "./ReentrantToken";
