/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOtterpadFund__factory } from "./IOtterpadFund__factory";
export { PresaleLock__factory } from "./PresaleLock__factory";
