/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PresaleLockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deposit"
      | "depositCounter"
      | "deposits"
      | "getSaleTokenBalance"
      | "getUserDepositIds"
      | "otterpadFund"
      | "redeem"
      | "saleToken"
      | "userDepositIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DepositLocked" | "RedeemUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDepositIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "otterpadFund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "saleToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDepositIds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSaleTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDepositIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "otterpadFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "saleToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDepositIds",
    data: BytesLike
  ): Result;
}

export namespace DepositLockedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    unlockUnixTime: BigNumberish,
    depositId: BigNumberish,
    blockNumber: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    unlockUnixTime: bigint,
    depositId: bigint,
    blockNumber: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    unlockUnixTime: bigint;
    depositId: bigint;
    blockNumber: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemUnlockedEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    depositId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    depositId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    depositId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PresaleLock extends BaseContract {
  connect(runner?: ContractRunner | null): PresaleLock;
  waitForDeployment(): Promise<this>;

  interface: PresaleLockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deposit: TypedContractMethod<
    [
      amount: BigNumberish,
      recipient: AddressLike,
      unlockUnixTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  depositCounter: TypedContractMethod<[], [bigint], "view">;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        recipient: string;
        amount: bigint;
        unlockUnixTime: bigint;
        depositId: bigint;
        isRedeemed: boolean;
      }
    ],
    "view"
  >;

  getSaleTokenBalance: TypedContractMethod<[], [bigint], "view">;

  getUserDepositIds: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  otterpadFund: TypedContractMethod<[], [string], "view">;

  redeem: TypedContractMethod<[depositId: BigNumberish], [void], "nonpayable">;

  saleToken: TypedContractMethod<[], [string], "view">;

  userDepositIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      recipient: AddressLike,
      unlockUnixTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        recipient: string;
        amount: bigint;
        unlockUnixTime: bigint;
        depositId: bigint;
        isRedeemed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSaleTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserDepositIds"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "otterpadFund"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[depositId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "saleToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userDepositIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DepositLocked"
  ): TypedContractEvent<
    DepositLockedEvent.InputTuple,
    DepositLockedEvent.OutputTuple,
    DepositLockedEvent.OutputObject
  >;
  getEvent(
    key: "RedeemUnlocked"
  ): TypedContractEvent<
    RedeemUnlockedEvent.InputTuple,
    RedeemUnlockedEvent.OutputTuple,
    RedeemUnlockedEvent.OutputObject
  >;

  filters: {
    "DepositLocked(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DepositLockedEvent.InputTuple,
      DepositLockedEvent.OutputTuple,
      DepositLockedEvent.OutputObject
    >;
    DepositLocked: TypedContractEvent<
      DepositLockedEvent.InputTuple,
      DepositLockedEvent.OutputTuple,
      DepositLockedEvent.OutputObject
    >;

    "RedeemUnlocked(address,uint256,uint256,uint256)": TypedContractEvent<
      RedeemUnlockedEvent.InputTuple,
      RedeemUnlockedEvent.OutputTuple,
      RedeemUnlockedEvent.OutputObject
    >;
    RedeemUnlocked: TypedContractEvent<
      RedeemUnlockedEvent.InputTuple,
      RedeemUnlockedEvent.OutputTuple,
      RedeemUnlockedEvent.OutputObject
    >;
  };
}
